usethis::create_package(here::here("."))
usethis::use_mit_license()
usethis::use_readme_rmd()
desc::desc_set("Depends", "R (>= 4.1)")
usethis::use_package("rlang")
usethis::use_package("zip")
usethis::use_package("dplyr")
usethis::use_package("purrr")
usethis::use_package("stringr")
usethis::use_package("jsonlite")
usethis::use_import_from("dplyr", c("pull", "filter", "left_join", "tibble"))
usethis::use_import_from("purrr", c("map_dfr", "pluck", "keep"))
usethis::use_import_from("stringr", c("str_detect", "str_extract"))
usethis::use_import_from("zip", "zip_list")
usethis::use_import_from("jsonlite", "read_json")
usethis::use_air()
usethis::use_git()
usethis::use_github()
usethis::use_github_action("check-standard")
usethis::use_github_actions_badge()
