devtools::build_readme()
devtools::spell_check()
devtools::check()
devtools::document()
rhub::rhub_doctor()
rhub::rhub_check()
# devtools::check(remote = TRUE, manual = TRUE)
# devtools::check_win_devel()
# usethis::use_release_issue(version = "0.1.0")
# devtools::release()
